### PR TITLE
Added new hook /  useCopyToClipboard ✨

### PR DESCRIPTION
**Pull request by mutasim77**
Hey, firstly, I wanted to say thanks, guys, for such a good UI library. I was playing with _Prismane_ for a few days and found it interesting. Also, I wanted to contribute (if it's possible), so here's my first contribution. I added the useCopyToClipboard hook. I hope it can be helpful in some way. ;)

### CODE REVIEW

**Comment by spleafy** [comment]
Hi, thank you for creating a pull request and wanting to contribute! This means the world to me! All kinds of contributions are always welcome and I would be more than happy to have you on board! This is a great hook and we will include it in the next minor version. Thanks again for contributing, I hope you continue to make Prismane a better library :)

**Review by spleafy — COMMENTED** [review]
Everything is excellent, I appreciate the effort in making a complex story and tests, it means a lot! The only thing I would recommend is to export the hook from the index.ts file in the /hooks directory because otherwise, the hook will not be accessible. Thank you for contributing!

**Comment by mutasim77** [comment]
Thank you for merging my PR. 
I also wanted to add docs about that hook, but it seems that the documentation is not in this repo.

**Comment by spleafy** [comment]
Hi, I would really appreciate adding some documentation to the website. You are right, the website repository is not in the PrismaneUI organization, it is a personal repo of mine. I will make it public now. If you are down to create a PR on it, I would greatly appreciate it! From: Mutasim Sent: Sunday, 24 September 2023 14:57To: prismaneui/prismaneCc: Martin Petrov; State changeSubject: Re: [prismaneui/prismane] Added new hook / useCopyToClipboard ✨ (PR #64) Thank you for merging my PR.I also wanted to add docs about that hook, but it seems that the documentation is not in this repo.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>

**Comment by spleafy** [comment]
Hi, I made the repo public. Here is the link: https://github.com/spleafy/prismane-website Whenever you have time, feel free to add the documentation about the hook. From: Mutasim Sent: Sunday, 24 September 2023 14:57To: prismaneui/prismaneCc: Martin Petrov; State changeSubject: Re: [prismaneui/prismane] Added new hook / useCopyToClipboard ✨ (PR #64) Thank you for merging my PR.I also wanted to add docs about that hook, but it seems that the documentation is not in this repo.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>

**Comment by spleafy** [comment]
Hi, I would really appreciate adding some documentation to the website. You are right, the website repository is not in the PrismaneUI organization, it is a personal repo of mine. I will make it public now. If you are down to create a PR on it, I would greatly appreciate it! This is the link to my personal repo: [https://github.com/spleafy/prismane-website](https://github.com/spleafy/prismane-website)

**Comment by mutasim77** [comment]
Thanks

**Pull request merged**
